name: Deploy to AWS App Runner

on:
  push:
    branches: [ "WTD-130-update-aws-yml-to-push-to-apprunner" ]

env:
  AWS_REGION: us-east-1

permissions:
  contents: read

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Login to Amazon ECR Public
      run: |
        aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/t1u7o7g8

    - name: Build, tag, and push image to Amazon ECR Public
      run: |
        cd backend
        docker build -t group_project . --no-cache
        docker tag group_project:latest public.ecr.aws/t1u7o7g8/group_project:test
        docker push public.ecr.aws/t1u7o7g8/group_project:test

    - name: Deploy to App Runner
      run: |
        aws apprunner start-deployment --region us-east-1 --service-arn arn:aws:apprunner:us-east-1:653252860125:service/what-to-do-backend_port/bf832f5cb02e4969969f5ed74f86ba73